dist: focal
branches:
  only:
    - master
    - development
    - /v\d+\.\d+\.\d+(-.+)?/
env:
  global:
    - TEST_WORKERS=5
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - &test-stage
      stage: test
      if: NOT (tag =~ /\d+\.\d+\.\d+/)
      language: ruby
      cache:
        bundler: true
        directories:
          - $TRAVIS_BUILD_DIR/node_modules
          - $TRAVIS_BUILD_DIR/spec/fixtures/vcr_cassettes
          - $TRAVIS_BUILD_DIR/public/packs-test
          - $TRAVIS_BUILD_DIR/public/assets
          - $TRAVIS_BUILD_DIR/tmp/cache/webpacker
          - /home/travis/.rvm/
      rvm:
        - 2.7.2
      bundler_args: --without development production
      addons:
        postgresql: "12"
        firefox: "latest"
        apt:
          packages:
            - imagemagick
            - tesseract-ocr
            - libgeos-dev
            - libproj-dev
            - postgresql-12-postgis-3
      env:
          - TEST_WORKER=0
      services:
        - postgresql
      before_install:
        - export PGPORT=$(pg_lsclusters -h | grep '^12 main' | cut -f3 -d' ')
        - nvm install 10
        - nvm use 10
      install:
        - npm install
        - gem install bundler
        - bundle config --local build.sassc --disable-march-tune-native
        - bundle install -j3 --without development production
      before_script:
        - echo ===[TEST_WORKER=$TEST_WORKER before_script $(date -u +%Y%m%d-%H%M%S)]===
        - cp config/application_settings.yml.travis config/application_settings.yml
        - cp config/database.yml.travis config/database.yml
        - cp config/secrets.yml.example config/secrets.yml
        - mkdir -p tmp/downloads
        - bundle exec rake db:create RAILS_ENV=test # database user by default is `travis`
        - bundle exec rake db:migrate RAILS_ENV=test
      script:
        - .travis/spec_runner.sh
    - <<: *test-stage
      env:
        - TEST_WORKER=1
    - <<: *test-stage
      env:
        - TEST_WORKER=2
    - <<: *test-stage
      env:
        - TEST_WORKER=3
    - <<: *test-stage
      env:
        - TEST_WORKER=4
    - stage: deliver
      if: (tag =~ /\d+\.\d+\.\d+/) OR (branch = development)
      language: minimal
      services:
        - docker
      install:
        - if [ "x$TRAVIS_TAG" != "x" ]; then export DOCKER_TAG=$(echo $TRAVIS_TAG | cut -c2-); else export DOCKER_TAG=latest; fi
        - export REVISION=$(git rev-parse HEAD | cut -c1-9)
        - docker build . -t sfgrp/taxonworks --build-arg REVISION=$REVISION --build-arg BUNDLER_WORKERS=3
      script:
        - .travis/docker-test.sh
      after_success:
        - |
          [ "$TRAVIS_REPO_SLUG" == "SpeciesFileGroup/taxonworks" ] && \
          [ "$TRAVIS_EVENT_TYPE" == "push" ] && \
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" && \
          docker tag sfgrp/taxonworks:latest sfgrp/taxonworks:$DOCKER_TAG && \
          docker push sfgrp/taxonworks:$DOCKER_TAG
notifications:
  email:
    recipients:
      - diapriid@gmail.com
      - ellocodelassembler@gmail.com
    on_failure: change
  webhooks: https://coveralls.io/webhook
