name: deliver

on:
  push:
    branches:
      - development
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'
  pull_request:
    branches:
      - development
  schedule:
    - cron: '0 0 * * *'

jobs:
  deliver:
    env:
      REF_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

    runs-on: ubuntu-latest
    steps:
    - name: Get startup date
      id: datetime
      run: echo "::set-output name=year_week::$(date -u +'%Y-%U')"

    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up Docker images cache
      id: docker_cache
      uses: actions/cache@v2
      with:
        path: .github/.docker-cache
        key: ${{ runner.os }}-docker-${{ steps.datetime.outputs.year_week }}-${{ hashFiles('**/package-lock.json', '**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-docker-${{ steps.datetime.outputs.year_week }}

    - name: Load Docker cache (if cache was hit)
      if: steps.docker_cache.outputs.cache-hit == 'true'
      run: docker load -i .github/.docker-cache/images.tar

    - name: Build the Docker image
      run: docker build . -t sfgrp/taxonworks --build-arg REVISION=$(echo $GITHUB_SHA | cut -c1-9) --build-arg BUNDLER_WORKERS=3

    - name: Run image tests
      run: .github/docker-tests/test.sh

    - name: Wait build workflow to complete successfully
      uses: actions/github-script@v3
      with:
        script: |
          const suiteId = (
            await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: process.env.REF_SHA,
              check_name: 'build (0)'
            })
          ).data.check_runs[0].check_suite.id

          const oneMinute = () => {
            return new Promise(resolve => {
              setTimeout(() => resolve(true), 60000)
            })
          }

          let suite, attempts = 15
          do {
            core.info(`Checking suite completed successfully (${attempts} remaining). [check_suite_id = ${suiteId}]`)
            suite = (
              await github.checks.getSuite({
                owner: context.repo.owner,
                repo: context.repo.repo,
                check_suite_id: suiteId
              })
            ).data
          } while(attempts-- && suite.status !== 'completed' && await oneMinute())

          if (suite.conclusion !== 'success') {
            core.setFailed(`Build workflow did not complete successfully. [status = '${suite.status}'; conclusion = '${suite.conclusion}']`);
          }

    - name: Login to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get tag for docker image
      id: docker_tag
      uses: actions/github-script@v3
      with:
        result-encoding: string
        script: |
          return github.ref.startsWith('refs/tags/v') ? github.ref.replace('refs/tags/v', '') : 'latest'

    - name: Push image to DockerHub
      if: ${{ github.event_name != 'pull_request' }}
      env:
        DOCKER_TAG: 'github-actions-${{steps.docker_tag.outputs.result}}'
      run: |
        docker tag sfgrp/taxonworks:latest sfgrp/taxonworks:$DOCKER_TAG
        docker push sfgrp/taxonworks:$DOCKER_TAG

    - name: Save Docker cache (if cache was NOT hit)
      if: steps.docker_cache.outputs.cache-hit != 'true'
      run: |
        mkdir -p .github/.docker-cache
        docker save -o .github/.docker-cache/images.tar $(docker history -q sfgrp/taxonworks | grep -v '^<missing>')
